//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> specialist { get; set; }
        public Nullable<int> id_the_purpose_of_the_appeal { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual The_purpose_of_the_appeal The_purpose_of_the_appeal { get; set; }
        public virtual Specialist Specialist1 { get; set; }
    }
}
